spring.application.name=spring-ai-mcp
server.port=8081

# H2
spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# MCP Server
spring.ai.mcp.server.name=ecommerce-db-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=sync

# init schema & data
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
